setup:
- type: resources
  resource_topic: /node_infos
  nodes:
  - name: /nodeA
    cpu_filter:
########### select one type: ###########
# 1 ####################################
#        type: mean
#        window_size: 200
# 2 ####################################
#        type: median
#        window_size: 200
# 3 ####################################
#        type: kmeans
#        window_size: 200
#        k_size: 10
# 4 ####################################
#        type: ewma                         # exponentially weighted moving average
#        window_size: 200                   # optional
#        decay_rate: 0.05                   # x = old_x * (1.0 - decay_rate) + new_x * decay_rate
# 5 ####################################
#        type: nofilter

###### select one deviation type: ######
# 1 ####################################
#        deviation_type: std_deviation
# 2 ####################################
#        deviation_type: min_max
    mem_filter:
########### select one type: ###########
# 1 ####################################
#        type: mean
#        window_size: 200
# 2 ####################################
#        type: median
#        window_size: 200
# 3 ####################################
#        type: kmeans
#        window_size: 200
#        k_size: 10
# 4 ####################################
#        type: ewma                         # exponentially weighted moving average
#        window_size: 200                   # optional
#        decay_rate: 0.05                   # x = old_x * (1.0 - decay_rate) + new_x * decay_rate
# 5 ####################################
#        type: nofilter

###### select one deviation type: ######
# 1 ####################################
#        deviation_type: std_deviation
# 2 ####################################
#        deviation_type: min_max
    states:
    - state: 'state1'
      number: 1
      cpu:
########### select one type: ###########
# 1 ####################################
#          type: student_t
#          true_mean: 0.10
#          std_deviation: 0.0003            # optional
#          significance_level: 0.05

# 2 ####################################
#          type: nominal_value

          value:
  ##### select one type for value: #####
  # 2.1.1 ################################
  #          type: gauss
  #          mean: 0.1
  #          std_deviation: 0.25
  # 2.1.2 ################################
  #          type: exact
  #          exact: 5.1
  # 2.1.3 ################################
  #          type: not
  #          exact_not: : 5.1
  # 2.1.4 ################################
  #          type: greather_than
  #          greater_than: 5.1
  # 2.1.5 ################################
  #          type: less_than
  #          less_than: 5.1
  # 2.1.6 ################################
  #          type: in_between
  #          lower_bound: 2.0
  #          upper_bound: 5.1
  # 2.1.7 ################################
  #          type: not_in_between
  #          lower_bound: 2.0
  #          upper_bound: 5.1

          deviation:
  #### select type(s) for deviation: ###    # has to be a list
  # 2.2.1 ################################
  #        - type: gauss
  #          mean: 0.1
  #          std_deviation: 0.25
  # 2.2.2 ################################
  #        - type: exact
  #          exact: 5.1
  # 2.2.3 ################################
  #        - type: not
  #          exact_not: : 5.1
  # 2.2.4 ################################
  #        - type: greather_than
  #          greater_than: 5.1
  # 2.2.5 ################################
  #        - type: less_than
  #          less_than: 5.1
  # 2.2.6 ################################
  #        - type: in_between
  #          lower_bound: 2.0
  #          upper_bound: 5.1
  # 2.2.7 ################################
  #        - type: not_in_between
  #          lower_bound: 2.0
  #          upper_bound: 5.1
      memory:
########### select one type: ###########
# 1 ####################################
#          type: student_t
#          true_mean: 0.10
#          std_deviation: 0.0003            # optional
#          significance_level: 0.05

# 2 ####################################
#          type: nominal_value

          value:
  ##### select one type for value: #####
  # 2.1.1 ################################
  #          type: gauss
  #          mean: 0.1
  #          std_deviation: 0.25
  # 2.1.2 ################################
  #          type: exact
  #          exact: 5.1
  # 2.1.3 ################################
  #          type: not
  #          exact_not: : 5.1
  # 2.1.4 ################################
  #          type: greather_than
  #          greater_than: 5.1
  # 2.1.5 ################################
  #          type: less_than
  #          less_than: 5.1
  # 2.1.6 ################################
  #          type: in_between
  #          lower_bound: 2.0
  #          upper_bound: 5.1
  # 2.1.7 ################################
  #          type: not_in_between
  #          lower_bound: 2.0
  #          upper_bound: 5.1

          deviation:
  #### select type(s) for deviation: ###    # has to be a list
  # 2.2.1 ################################
  #        - type: gauss
  #          mean: 0.1
  #          std_deviation: 0.25
  # 2.2.2 ################################
  #        - type: exact
  #          exact: 5.1
  # 2.2.3 ################################
  #        - type: not
  #          exact_not: : 5.1
  # 2.2.4 ################################
  #        - type: greather_than
  #          greater_than: 5.1
  # 2.2.5 ################################
  #        - type: less_than
  #          less_than: 5.1
  # 2.2.6 ################################
  #        - type: in_between
  #          lower_bound: 2.0
  #          upper_bound: 5.1
  # 2.2.7 ################################
  #        - type: not_in_between
  #          lower_bound: 2.0
  #          upper_bound: 5.1
